import { PODCAST_COVERS, PLAYER_EPISODES } from '../../data/podcastCatalog'
import type { HomeFeedData } from './types'

export const MOCK_HOME_FEED: HomeFeedData = {
  featured: {
    id: 'feat-1',
    showName: PLAYER_EPISODES.jayShetty.showName,
    episodeTitle: PLAYER_EPISODES.jayShetty.episodeTitle,
    description:
      'Jay Shetty on why monks meditate at sunrise — and how a simple morning ritual can reset your focus for the whole day.',
    artworkTone: 'terracotta',
    coverSrc: PODCAST_COVERS.jayShetty,
    durationLabel: '36 min',
  },
  recommendations: [
    {
      id: 'rec-1',
      showName: 'Hard Fork',
      episodeTitle: 'Our Field Trip to Google I/O + A Sit-Down With Sundar Pichai',
      description: 'Kevin Roose and Casey Newton report from Google I/O and sit down with Sundar Pichai.',
      artworkTone: 'indigo',
      coverSrc: PODCAST_COVERS.hardFork,
      durationLabel: '58 min',
    },
    {
      id: 'rec-2',
      showName: PLAYER_EPISODES.wsj.showName,
      episodeTitle: PLAYER_EPISODES.wsj.episodeTitle,
      description: 'How Silicon Valley Bank collapsed — and what it meant for tech startups.',
      artworkTone: 'sand',
      coverSrc: PODCAST_COVERS.wsj,
      durationLabel: '12 min',
    },
    {
      id: 'rec-3',
      showName: PLAYER_EPISODES.foreignAffairs.showName,
      episodeTitle: PLAYER_EPISODES.foreignAffairs.episodeTitle,
      description: 'John Mearsheimer on realism, leadership, and the limits of American power.',
      artworkTone: 'forest',
      coverSrc: PODCAST_COVERS.foreignAffairs,
      durationLabel: '42 min',
    },
    {
      id: 'rec-4',
      showName: 'The Ezra Klein Show',
      episodeTitle: 'Best Of: Yuval Noah Harari on the Age of AI',
      description: 'Ezra Klein revisits his conversation with Yuval Noah Harari on AI and human agency.',
      artworkTone: 'plum',
      coverSrc: PODCAST_COVERS.ezraKlein,
      durationLabel: '52 min',
    },
    {
      id: 'rec-5',
      showName: 'WorkLife with Adam Grant',
      episodeTitle: 'How to Stop Procrastinating',
      description: 'Adam Grant on the psychology of procrastination and how to beat it.',
      artworkTone: 'ocean',
      coverSrc: PODCAST_COVERS.workLife,
      durationLabel: '28 min',
    },
    {
      id: 'rec-6',
      showName: 'Decoder',
      episodeTitle: 'Why Spotify wants to be everything',
      description: 'Nilay Patel on Spotify’s push beyond music into a full audio platform.',
      artworkTone: 'rust',
      coverSrc: PODCAST_COVERS.decoder,
      durationLabel: '41 min',
    },
  ],
  newEpisodes: [
    {
      id: 'new-1',
      showName: 'Radiolab',
      episodeTitle: 'The Wubi Effect',
      durationLabel: '42 min',
      publishedLabel: '2h ago',
      isNew: true,
      artworkTone: 'coral',
      coverSrc: PODCAST_COVERS.radiolab,
    },
    {
      id: 'new-2',
      showName: 'Planet Money',
      episodeTitle: 'Why rent is so high',
      durationLabel: '28 min',
      publishedLabel: '6h ago',
      isNew: true,
      artworkTone: 'gold',
      coverSrc: PODCAST_COVERS.planetMoney,
    },
    {
      id: 'new-3',
      showName: 'Fresh Air',
      episodeTitle: 'Best Of: Actor Nicolas Cage',
      durationLabel: '36 min',
      publishedLabel: 'Yesterday',
      isNew: false,
      artworkTone: 'moss',
      coverSrc: PODCAST_COVERS.freshAir,
    },
    {
      id: 'new-4',
      showName: 'SmartLess',
      episodeTitle: 'Tom Hanks',
      durationLabel: '55 min',
      publishedLabel: 'Yesterday',
      isNew: false,
      artworkTone: 'berry',
      coverSrc: PODCAST_COVERS.smartLess,
    },
  ],
}
